"""edge_client_smart.py — Round-0 Bootstrap + Acceptance-Aware Fallback.

Two mechanisms, each toggleable, each tied to a measured phenomenon:

  STEP 1 — Round-0 Bootstrap (--bootstrap M):
    Round 0 acceptance is ~0.29 (vs ~0.80 steady). Instead of wasting a
    Jetson draft on that round, ask H200 to AR-generate the first M tokens
    directly (H200 single-token AR is ~6ms). Then enter normal edge-cloud SD.

  STEP 2 — Acceptance-Aware Fallback (--fallback-k K --fallback-thresh T):
    After the first K SD rounds, compute observed acceptance. If it's below
    T, this request is a poor fit for edge draft (e.g. open-ended MT-Bench).
    Switch to cloud-only AR for the remainder: H200 generates the rest in
    one /generate call (162 tok/s) instead of crawling at ~10 tok/s.

Requires verify_server with the /generate endpoint (apply patch_verify_server.py).
RemoteVerifier must have .generate() (apply verifier_ext.py).
"""
from __future__ import annotations
import time
from dataclasses import dataclass, field
from typing import List, Optional, Tuple, Dict, Any

from edge.edge_client import EdgeClient, GenerationMetrics
from edge.verifier import VerifierBase, VerifyResult
import edge.verifier_ext as verifier_ext  # noqa: F401  (attaches .generate to RemoteVerifier)


@dataclass
class SmartMetrics(GenerationMetrics):
    bootstrap_tokens: int = 0
    fell_back: bool = False
    fallback_round: int = -1
    acceptance_at_fallback: float = 0.0
    cloud_tokens: int = 0          # tokens generated by cloud fallback


class SmartEdgeClient(EdgeClient):
    def __init__(self, draft_url: str = "http://localhost:8080",
                 bootstrap_m: int = 0,
                 fallback_k: int = 0,
                 fallback_thresh: float = 0.0,
                 fallback_max_tokens: int = 512):
        super().__init__(draft_url=draft_url)
        self.bootstrap_m = bootstrap_m            # 0 = disabled
        self.fallback_k = fallback_k              # 0 = disabled
        self.fallback_thresh = fallback_thresh
        self.fallback_max_tokens = fallback_max_tokens

    def generate(self, messages, verifier: VerifierBase, gamma: int = 2,
                 max_tokens: int = 512, temperature: float = 0.0,
                 eos_id: Optional[int] = None,
                 no_think: bool = False) -> Tuple[str, SmartMetrics]:
        # Qwen3 thinking off: append /no_think to the last user turn.
        if no_think:
            messages = [dict(mm) for mm in messages]
            for mm in reversed(messages):
                if mm.get("role") == "user":
                    mm["content"] = mm.get("content", "").rstrip() + " /no_think"
                    break
        prompt_text = self.apply_chat_template(messages, add_generation_prompt=True)
        prompt_ids = self.tokenize(prompt_text, add_special=False)
        if eos_id is None:
            props = self.props()
            eos_id = (props.get("default_generation_settings", {}).get("eos_token_id")
                      or props.get("eos_token_id") or 128009)

        gen_start = len(prompt_ids)
        m = SmartMetrics()
        t_start = time.perf_counter()
        ids = list(prompt_ids)

        has_remote_gen = hasattr(verifier, "generate")

        # ---------- STEP 1: Round-0 bootstrap ----------
        if self.bootstrap_m > 0 and has_remote_gen:
            tok_ids, stop, ms = verifier.generate(
                prompt_ids=ids, max_tokens=self.bootstrap_m,
                temperature=temperature, eos_id=eos_id,
            )
            ids.extend(tok_ids)
            m.bootstrap_tokens = len(tok_ids)
            m.verify_time_ms += ms     # count bootstrap under "verify" (cloud) time
            if stop:
                m.total_output_tokens = len(ids) - gen_start
                m.wall_time_s = time.perf_counter() - t_start
                return self._finish(ids, gen_start, eos_id), m

        # ---------- Main edge-cloud SD loop ----------
        round_idx = 0
        while len(ids) - gen_start < max_tokens:
            # ---- STEP 2: acceptance-aware fallback check ----
            if (self.fallback_k > 0 and round_idx == self.fallback_k
                    and has_remote_gen and not m.fell_back):
                obs_accept = m.n_accepted / max(1, m.n_draft_proposed)
                if obs_accept < self.fallback_thresh:
                    # Switch to cloud-only AR for the remainder
                    remaining = max_tokens - (len(ids) - gen_start)
                    tok_ids, stop, ms = verifier.generate(
                        prompt_ids=ids, max_tokens=remaining,
                        temperature=temperature, eos_id=eos_id,
                    )
                    ids.extend(tok_ids)
                    m.fell_back = True
                    m.fallback_round = round_idx
                    m.acceptance_at_fallback = obs_accept
                    m.cloud_tokens = len(tok_ids)
                    m.verify_time_ms += ms
                    break

            # Draft
            t0 = time.perf_counter()
            draft_ids, draft_lps = self.draft(ids, gamma, temperature)
            draft_ms = (time.perf_counter() - t0) * 1000.0
            if not draft_ids:
                break
            short_draft_stop = len(draft_ids) < gamma
            remaining = max_tokens - (len(ids) - gen_start)
            if len(draft_ids) > remaining:
                draft_ids = draft_ids[:remaining]; draft_lps = draft_lps[:remaining]

            vr: VerifyResult = verifier.verify(
                prompt_ids=ids, draft_ids=draft_ids,
                draft_logprobs=draft_lps, temperature=temperature, eos_id=eos_id,
            )
            ids.extend(vr.accepted_ids)
            if vr.bonus_id is not None:
                ids.append(vr.bonus_id)

            m.n_rounds += 1
            m.n_draft_proposed += len(draft_ids)
            m.n_accepted += vr.n_accepted
            m.n_bonus += (1 if vr.bonus_id is not None else 0)
            m.draft_time_ms += draft_ms
            m.verify_time_ms += vr.verify_time_ms
            m.network_time_ms += vr.network_time_ms
            m.rounds.append({
                "round_idx": round_idx, "gamma": len(draft_ids),
                "n_accepted": vr.n_accepted, "draft_ms": draft_ms,
                "verify_ms": vr.verify_time_ms, "network_ms": vr.network_time_ms,
            })

            if vr.should_stop or short_draft_stop:
                break
            if vr.n_accepted == 0 and vr.bonus_id is None:
                break
            round_idx += 1

        m.total_output_tokens = len(ids) - gen_start
        m.wall_time_s = time.perf_counter() - t_start
        return self._finish(ids, gen_start, eos_id), m

    def _finish(self, ids, gen_start, eos_id) -> str:
        gen_ids = ids[gen_start:]
        if eos_id is not None and gen_ids and gen_ids[-1] == eos_id:
            gen_ids = gen_ids[:-1]
        return self.detokenize(gen_ids)
